# Generated by Django 2.1.7 on 2019-03-13 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_remove_like_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='component',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='components.Component'),
        ),
    ]
