# Generated by Django 3.1.2 on 2020-10-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='code',
        ),
        migrations.AddField(
            model_name='component',
            name='code',
            field=models.CharField(default='Im Arman', max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
